services:
  - name: securebank-backend
    buildCommand: mvn clean dependency:resolve -U package -DskipTests
    startCommand: java -jar target/banking-system-1.0.0.jar
    envVars:
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_USERNAME
        value: shreyadornalwar@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: "ceyk scxs rbrf hyts"
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        sync: false  # Do not expose in logs
      - key: SQL_INIT_MODE
        value: "always"
      - key: JAVA_OPTS
        value: "-Xmx512m"
