services:
  - name: securebank-backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/banking-system-1.0.0.jar
    envVars:
      - key: DB_URL
        value: "jdbc:postgresql://dpg-d7710a8gjchc73dmkng0-a.oregon-postgres.render.com:5432/bankdb_y3zd"
      - key: DB_USER
        value: "bankuser"
      - key: DB_PASS
        value: "hDmIeJMlyj8C"
      - key: MAIL_PASSWORD
        sync: false
      - key: PORT
        value: "8080"

databases:
  - name: securebank-db
    databaseName: bankdb
    plan: free
