services:
  - name: securebank-backend
    buildCommand: mvn clean dependency:resolve -U package -DskipTests
    startCommand: java -jar target/banking-system-1.0.0.jar
    envVars:
      - key: MAIL_PASSWORD
        sync: false
      - key: PORT
        value: "8080"
